// Tsubame/examples/todo/src/App.tsx
import { createEffect, createMemo, createSignal } from 'solid-js';
import { CssGallery } from './CssGallery';
import type { DetectModeResult } from '@tsubame/app';
import { AddForm } from './components/AddForm';
import { AppBar } from './components/AppBar';
import { EmptyState, Footer, Header, SelectableNote } from './components/TaskCard';
import { TodoRow } from './components/TodoRow';
import { Toolbar } from './components/Toolbar';
import {
  loadTheme,
  palette,
  saveTheme,
  type AccentKey,
  type Theme,
} from './theme';
import {
  add,
  canReorder,
  clearDone,
  completion,
  editText,
  moveDown,
  moveUp,
  remove,
  SEED,
  toggleDone,
  visibleTodos,
  type Filter,
  type Priority,
  type SortMode,
  type Todo,
} from './todo-model';

/** タスク画面とギャラリー画面のどちらを表示するか。 */
export type Page = 'tasks' | 'gallery';

export interface TodoAppProps {
  detected: DetectModeResult;
}

function seedTodos(): Todo[] {
  return SEED.map((todo) => ({ ...todo }));
}

export function TodoApp(props: TodoAppProps) {
  const initialPage: Page =
    new URLSearchParams(window.location.search).get('page') === 'gallery' ? 'gallery' : 'tasks';
  const [page, setPage] = createSignal<Page>(initialPage);
  const [todos, setTodos] = createSignal<Todo[]>(seedTodos());
  const [filter, setFilter] = createSignal<Filter>('all');
  const [sort, setSort] = createSignal<SortMode>('manual');
  const [draftPrio, setDraftPrio] = createSignal<Priority>(2);
  const [draft, setDraft] = createSignal('');
  // インライン編集の対象行（null=非編集）と、その編集中テキスト。
  const [editingId, setEditingId] = createSignal<number | null>(null);
  const [editDraft, setEditDraft] = createSignal('');
  let nextId = 1000;

  // テーマ・アクセントは localStorage で永続化（#247 の方針）。既定はライト。
  const initialPrefs = loadTheme(window.localStorage);
  const [theme, setTheme] = createSignal<Theme>(initialPrefs.theme);
  const [accent, setAccent] = createSignal<AccentKey>(initialPrefs.accent);
  const colors = createMemo(() => palette(theme(), accent()));
  createEffect(() => saveTheme(window.localStorage, { theme: theme(), accent: accent() }));

  // Hayate アプリ外の素 HTML オーバーレイ（#renderer-switch）へ現在パレットを橋渡しする。
  // Hayate CSS には custom properties が無いため、document の CSS 変数経由で同期し、
  // テーマ/アクセント変更にライブ追従させる（正本はここ・index.html は boot 近似）。
  createEffect(() => {
    const p = colors();
    const root = document.documentElement.style;
    root.setProperty('--rsw-bg', p.rail);
    root.setProperty('--rsw-line', p.line);
    root.setProperty('--rsw-text', p.muted);
    root.setProperty('--rsw-ink', p.ink);
    root.setProperty('--rsw-hover', p.panel3);
    root.setProperty('--rsw-on-accent', p.black);
    root.setProperty('--rsw-accent', p.accent);
  });

  const toggleTheme = () => setTheme((current) => (current === 'dark' ? 'light' : 'dark'));

  const visible = createMemo(() => visibleTodos(todos(), filter(), sort()));
  const summary = createMemo(() => completion(todos()));

  const addTask = () => {
    const text = draft();
    if (!text.trim()) return;
    setTodos(add(todos(), { id: nextId++, text, prio: draftPrio() }));
    setDraft('');
  };

  const toggle = (id: number) => setTodos(toggleDone(todos(), id));
  const removeTask = (id: number) => setTodos(remove(todos(), id));
  const clearCompleted = () => setTodos(clearDone(todos()));
  const moveTaskUp = (id: number) => setTodos(moveUp(todos(), id));
  const moveTaskDown = (id: number) => setTodos(moveDown(todos(), id));

  // インライン編集: クリックで開始、Enter/blur で確定、Escape で取消。
  const beginEdit = (todo: Todo) => {
    setEditingId(todo.id);
    setEditDraft(todo.text);
  };
  const commitEdit = () => {
    const id = editingId();
    if (id === null) return; // Escape 後の blur など、二重確定を無視する。
    setTodos(editText(todos(), id, editDraft())); // 空文字はモデル側で無視。
    setEditingId(null);
  };
  const cancelEdit = () => setEditingId(null);

  return (
    <view style={{
      width: '100%',
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      backgroundColor: colors().bg,
      defaultColor: colors().text,
      defaultFontSize: 14,
      defaultFontFamily: 'Inter, Segoe UI, system-ui, sans-serif',
    }}>
      <AppBar
        page={page()}
        setPage={setPage}
        detected={props.detected}
        colors={colors()}
        theme={theme()}
        accent={accent()}
        onToggleTheme={toggleTheme}
        onAccent={setAccent}
      />

      {page() === 'gallery'
        ? <CssGallery colors={colors()} />
        : <scroll-view
          style={{
            flexGrow: 1,
            width: '100%',
            height: '100%',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            paddingTop: 28,
            paddingBottom: 28,
            paddingLeft: 16,
            paddingRight: 16,
            backgroundColor: colors().bg,
          }}
          // 狭幅では左右余白を詰める。カードが画面端へ密着しないよう左右パディングは残す。
          styleVariants={[
            { condition: { maxWidth: 719 }, style: { paddingTop: 16, paddingBottom: 16, paddingLeft: 12, paddingRight: 12 } },
          ]}
        >
          <view
            style={{
              width: 620,
              maxWidth: '100%',
              display: 'flex',
              flexDirection: 'column',
              gap: 16,
              padding: 22,
              backgroundColor: colors().panel,
              borderRadius: 18,
              borderWidth: 1,
              borderStyle: 'solid',
              borderColor: colors().line,
              boxShadow: [{ offsetX: 0, offsetY: 18, blur: 40, spread: -8, color: colors().shadow, inset: false }],
            }}
            // 狭幅では余白と角丸を詰める（本物の @media・ADR-0081）。
            styleVariants={[
              { condition: { maxWidth: 719 }, style: { padding: 14, gap: 12, borderRadius: 12 } },
            ]}
          >
            <Header colors={colors()} remaining={summary().remaining} total={summary().total} percent={summary().percent} />
            <SelectableNote colors={colors()} />
            <AddForm
              colors={colors()}
              draft={draft()}
              prio={draftPrio()}
              onInput={setDraft}
              onPrio={setDraftPrio}
              onAdd={addTask}
            />
            <Toolbar colors={colors()} filter={filter()} sort={sort()} onFilter={setFilter} onSort={setSort} />
            <view style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {visible().length === 0
                ? <EmptyState colors={colors()} />
                : visible().map((todo) => (
                  <TodoRow
                    colors={colors()}
                    todo={todo}
                    reorderable={canReorder(sort())}
                    editing={editingId() === todo.id}
                    editDraft={editDraft()}
                    onToggle={() => toggle(todo.id)}
                    onRemove={() => removeTask(todo.id)}
                    onBeginEdit={() => beginEdit(todo)}
                    onEditInput={setEditDraft}
                    onCommitEdit={commitEdit}
                    onCancelEdit={cancelEdit}
                    onMoveUp={() => moveTaskUp(todo.id)}
                    onMoveDown={() => moveTaskDown(todo.id)}
                  />
                ))}
            </view>
            <view style={{ height: 1, backgroundColor: colors().line }} />
            <Footer colors={colors()} percent={summary().percent} onClearDone={clearCompleted} />
          </view>
        </scroll-view>}
    </view>
  );
}

// Tsubame/examples/react-todo/src/App.tsx
import { useMemo, useState } from 'react';
import type { HayateCssStyle } from '@tsubame/renderer-protocol';

interface Todo {
  id: number;
  text: string;
  done: boolean;
}

const SEED: readonly Todo[] = [
  { id: 1, text: 'tsubame-react のデモを動かす', done: true },
  { id: 2, text: 'view / text / button を組む', done: false },
  { id: 3, text: 'text-input で新規タスクを追加', done: false },
];

// 単一カードの落ち着いたダークパレット（デモ用にハードコード）。
const C = {
  bg: '#0b1020',
  panel: '#141a2e',
  line: '#26304a',
  ink: '#e7edf8',
  muted: '#8a97b3',
  accent: '#14b8a6',
  black: '#06140f',
  danger: '#f0648c',
} as const;

export function App() {
  const [todos, setTodos] = useState<Todo[]>(() => SEED.map((t) => ({ ...t })));
  const [draft, setDraft] = useState('');
  const [nextId, setNextId] = useState(1000);

  const remaining = useMemo(() => todos.filter((t) => !t.done).length, [todos]);

  const add = () => {
    const text = draft.trim();
    if (!text) return;
    setTodos((prev) => [{ id: nextId, text, done: false }, ...prev]);
    setNextId((n) => n + 1);
    setDraft('');
  };

  const toggle = (id: number) =>
    setTodos((prev) => prev.map((t) => (t.id === id ? { ...t, done: !t.done } : t)));

  const remove = (id: number) => setTodos((prev) => prev.filter((t) => t.id !== id));

  const clearDone = () => setTodos((prev) => prev.filter((t) => !t.done));

  return (
    <view style={shell}>
      <scroll-view style={page}>
        <view style={card}>
          <view style={{ display: 'flex', flexDirection: 'row', alignItems: 'baseline', gap: 10 }}>
            <text style={{ defaultColor: C.ink, defaultFontSize: 22, fontWeight: 700 }}>
              React TODO
            </text>
            <text style={{ defaultColor: C.muted, defaultFontSize: 13 }}>
              {`残り ${remaining} / ${todos.length} 件`}
            </text>
          </view>

          <view style={{ display: 'flex', flexDirection: 'row', gap: 8 }}>
            <view style={{ flexGrow: 1 }}>
              <text-input
                value={draft}
                placeholder="新しいタスクを入力…"
                style={input}
                onInput={(e) => setDraft(e.value ?? '')}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') add();
                }}
              />
            </view>
            <button style={primaryBtn} onClick={add}>
              追加
            </button>
          </view>

          <view style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {todos.length === 0 ? (
              <text style={{ defaultColor: C.muted, defaultFontSize: 14 }}>
                タスクはありません 🎉
              </text>
            ) : (
              todos.map((todo) => (
                <view key={todo.id} style={row}>
                  <button style={check(todo.done)} onClick={() => toggle(todo.id)}>
                    {todo.done ? '✓' : ''}
                  </button>
                  <view style={{ flexGrow: 1 }} onClick={() => toggle(todo.id)}>
                    <text style={label(todo.done)}>{todo.text}</text>
                  </view>
                  <button style={removeBtn} onClick={() => remove(todo.id)}>
                    ×
                  </button>
                </view>
              ))
            )}
          </view>

          <view style={{ height: 1, backgroundColor: C.line }} />

          <view style={{ display: 'flex', flexDirection: 'row', justifyContent: 'flex-end' }}>
            <button style={ghostBtn} onClick={clearDone}>
              完了済みを削除
            </button>
          </view>
        </view>
      </scroll-view>
    </view>
  );
}

const shell: HayateCssStyle = {
  width: '100%',
  height: '100%',
  display: 'flex',
  flexDirection: 'column',
  backgroundColor: C.bg,
  defaultColor: C.ink,
  defaultFontSize: 14,
  defaultFontFamily: 'Inter, Segoe UI, system-ui, sans-serif',
};

const page: HayateCssStyle = {
  flexGrow: 1,
  width: '100%',
  height: '100%',
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  paddingTop: 36,
  paddingBottom: 36,
  paddingLeft: 16,
  paddingRight: 16,
};

const card: HayateCssStyle = {
  width: 520,
  maxWidth: '100%',
  display: 'flex',
  flexDirection: 'column',
  gap: 16,
  padding: 22,
  backgroundColor: C.panel,
  borderRadius: 16,
  borderWidth: 1,
  borderStyle: 'solid',
  borderColor: C.line,
  boxShadow: [{ offsetX: 0, offsetY: 18, blur: 40, spread: -8, color: '#00000066', inset: false }],
};

const input: HayateCssStyle = {
  width: '100%',
  height: 40,
  paddingLeft: 12,
  paddingRight: 12,
  backgroundColor: C.bg,
  defaultColor: C.ink,
  defaultFontSize: 14,
  borderRadius: 9,
  borderWidth: 1,
  borderStyle: 'solid',
  borderColor: C.line,
};

const primaryBtn: HayateCssStyle = {
  height: 40,
  paddingLeft: 18,
  paddingRight: 18,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: C.accent,
  defaultColor: C.black,
  defaultFontSize: 13,
  fontWeight: 700,
  borderRadius: 9,
  cursor: 'pointer',
  ':hover': { opacity: 0.9 },
};

const row: HayateCssStyle = {
  display: 'flex',
  flexDirection: 'row',
  alignItems: 'center',
  gap: 10,
  padding: 10,
  backgroundColor: C.bg,
  borderRadius: 10,
  borderWidth: 1,
  borderStyle: 'solid',
  borderColor: C.line,
};

const check = (done: boolean): HayateCssStyle => ({
  width: 24,
  height: 24,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: done ? C.accent : 'transparent',
  defaultColor: C.black,
  defaultFontSize: 14,
  fontWeight: 700,
  borderRadius: 6,
  borderWidth: 1,
  borderStyle: 'solid',
  borderColor: done ? C.accent : C.line,
  cursor: 'pointer',
});

const label = (done: boolean): HayateCssStyle => ({
  defaultColor: done ? C.muted : C.ink,
  defaultFontSize: 14,
  textDecoration: done ? 'line-through' : 'none',
  cursor: 'pointer',
});

const removeBtn: HayateCssStyle = {
  width: 28,
  height: 28,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: 'transparent',
  defaultColor: C.muted,
  defaultFontSize: 18,
  borderRadius: 6,
  cursor: 'pointer',
  ':hover': { defaultColor: C.danger },
};

const ghostBtn: HayateCssStyle = {
  height: 34,
  paddingLeft: 14,
  paddingRight: 14,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: 'transparent',
  defaultColor: C.muted,
  defaultFontSize: 13,
  borderRadius: 8,
  borderWidth: 1,
  borderStyle: 'solid',
  borderColor: C.line,
  cursor: 'pointer',
  ':hover': { defaultColor: C.ink, borderColor: C.muted },
};
